Task 32
Appers-lab/sss-theme pull request #60
Opened 2021-07-03 17:17 UTC by j-ae

[Task 32](https://github.com/Appers-lab/billihomes-frontend/issues/50)
@pmvald, please review.

2021-07-07 20:01 UTC, pmvald requested changes
@j-ae This is cool. I'm happy with the design. The only thing is that we should use ::part to apply styles directly to the label instead of applying style to the li element. I made code reviews regarding this. Otehr than that it is good.

2021-07-08 05:00 UTC, j-ae commented on -sass/styles/_lists.m.scss
> +  &--no-item-border {
".s-checkox-list" isn't a custom-element. so .s-checkox-list::part(label) won't work. right?

2021-07-08 05:07 UTC, j-ae commented
I applied the style of the bottom line to <label> using ::part. (it was applied to <li> before.)

2021-07-13 18:39 UTC, pmvald approved these changes
@j-ae cool!

2021-07-13 18:39 UTC, merged